# Generated by Django 5.1.6 on 2026-01-15 09:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievementpage',
            name='body',
        ),
        migrations.AddField(
            model_name='achievementpage',
            name='achievements',
            field=wagtail.fields.StreamField([('achievement', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}),
        ),
    ]
