# Generated by Django 5.1.6 on 2026-01-15 10:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_achievementpage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementpage',
            name='achievements',
            field=wagtail.fields.StreamField([('achievement', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'ul', 'ol', 'link']}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}),
        ),
    ]
