# Generated by Django 5.1.6 on 2026-01-15 10:29

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_achievementpage_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementpage',
            name='achievements',
            field=wagtail.fields.StreamField([('achievement', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Achievement heading (plain text)', 'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h3', 'bold', 'italic', 'ul', 'ol', 'link'], 'help_text': 'Use toolbar for headings and lists'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Optional supporting image', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2)]], {})}),
        ),
    ]
